version: '3'

networks:
  prochnow:

services:
  sitegu:
    build:
      context: .
      dockerfile: ./gustavo/Dockerfile
    container_name: "sitegu"
    restart: "no"
    ports:
      - 9001:80
    volumes:
      - ./gustavo:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - prochnow

  bd-gu:
    image: mysql:5.7
    env_file:
      - ./mysql/.env
    container_name: "bd-gu"
    restart: "no"
    ports:
      - 3306:4306
    volumes:
      - ./mysql/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./mysql/conf/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    networks:
      - prochnow
    
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_mamanger
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx-pm/data:/data
      - ./nginx-pm/letsencrypt:/etc/letsencrypt
    networks:
      - prochnow
 
  
