version: '3'

networks:
  prochnow:

services:
  sitegu:
    build:
      context: .
      dockerfile: ./gustavo/Dockerfile
    container_name: "sitegu"
    restart: "no"
    ports:
      - 9001:80
    volumes:
      - ./gustavo:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - prochnow

  bd-gu:
    image: mysql:5.7
    env_file:
      - ./mysql/.env
    container_name: "bd-gu"
    restart: "no"
    ports:
      - 3306:4306
    volumes:
      - ./mysql/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./mysql/conf/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    networks:
      - prochnow
    

  
